### GET ALL Orders
GET http://localhost:3000/api/order

### CREATE New Order
POST http://localhost:3000/api/order
Content-Type: application/json

{
  "user": "66ff8c2e2b9d1e47a84cc111",
  "orderItems": [
    {
      "product": "66ff8cbb2b9d1e47a84cc222",
      "quantity": 2,
      "priceAtOrder": 15000
    },
    {
      "product": "66ff8d0c2b9d1e47a84cc333",
      "quantity": 1,
      "priceAtOrder": 25000
    }
  ],
  "totalAmount": 55000
}

### GET Order by ID
GET http://localhost:3000/api/order/66ff8e0f2b9d1e47a84cc444

### UPDATE Order
PUT http://localhost:3000/api/order/66ff8e0f2b9d1e47a84cc444
Content-Type: application/json

{
  "status": "Shipped"
}

### DELETE Order
DELETE http://localhost:3000/api/order/66ff8e0f2b9d1e47a84cc444